### ISSUE TITLE
关于代码的咨询

### ISSUE THREAD

**Issue by doubibobo** [mdswyz/DiCMoR#1]
您好，这篇工作研究的内容非常有意义，有两个代码问题想向您请教！
1. 在random missing protocol实验中，下面两行代码应该如何解释，尤其miss_1感觉没啥规律呀？
https://github.com/mdswyz/DiCMoR/blob/3d7e617ea173232ee8ae652a7fe7964d4b4485e1/trains/singleTask/DICMOR.py#L64
https://github.com/mdswyz/DiCMoR/blob/3d7e617ea173232ee8ae652a7fe7964d4b4485e1/trains/singleTask/DICMOR.py#L65
2. 在dicmor.py脚本中，模态生成部分您数据的形状为<B, D, T>，T维为啥会放在最后一维？您模型中有些子模块不参与训练，那他们对应的权重是在complete data上训练好的吗？
https://github.com/mdswyz/DiCMoR/blob/3d7e617ea173232ee8ae652a7fe7964d4b4485e1/trains/singleTask/model/dicmor.py#L144

还请大佬解答！

**Comment by mdswyz** [comment]
同学你好，感谢关注！
对于第一个问题，首先miss_2代表缺失2个模态的样本百分比，miss_1代表缺失1个模态的百分比. 我以MR=0.1为例子，设缺失2个模态的样本比例为a，缺失1个模态的样本比例为b，总体缺失率为0.1，那么可以得到2*a+b=3*0.1=0.3，可以看出a和b满足等式:2a+b=0.3，在代码中我们选择a=0.1，b=0.1来进行MR=0.1的实验。
对于第二个问题，T维为啥会放在最后一维为了迎合卷积层的输入格式，并且浅层特征提取器是预训练（complete data），如果不冻住这部分参数，模态的分布是无法捕捉的，因为每次迭代都在变化。

**Comment by doubibobo** [comment]
谢谢您的回答！我还有一个问题，`pt`文件夹下用`complete multimodal data`数据训练的模型是用`DiCMoR (mr=0.0)`训练的吗，还是`MulT`训练的，取了`conv1d`层？

**Comment by mdswyz** [comment]
> 谢谢您的回答！我还有一个问题，`pt`文件夹下用`complete multimodal data`数据训练的模型是用`DiCMoR (mr=0.0)`训练的吗，还是`MulT`训练的，取了`conv1d`层？

DiCMoR (mr=0.0)
