### ISSUE TITLE
subNets文件夹下BertTextEncoder内导入问题

### ISSUE THREAD

**Issue by FAFUxrhuang** [mdswyz/DiCMoR#2]
在BertTextEncoder.py文件下，from transformers import BertModel, BertTokenizer, RobertaModel, RobertaTokenizer，这四个并没有出现在您的transformers 文件夹下，这个要怎么处理呢？

**Comment by mdswyz** [comment]
transformers是[Hugging Face](https://huggingface.co/)提出的一个库，你可以pip install transformers来解决
