### ISSUE TITLE
cannot reproduce code

### ISSUE THREAD

**Issue by Duyih25** [mdswyz/DiCMoR#3]
I met this issue : 
RuntimeError: Error(s) in loading state_dict for DICMOR:
	Missing key(s) in state_dict: "flow_l.blocks.0.flows.0.actnorm.loc", "flow_l.blocks.0.flows.0.actnorm.scale", "flow_l.blocks.0.flows.0.actnorm.initialized", "flow_l.blocks.0.flows.0.invconv.weight", "flow_l.blocks.0.flows.0.coupling.net.0.weight", "flow_l.blocks.0.flows.0.coupling.net.0.bias", "flow_l.blocks.0.flows.0.coupling.net.2.weight", "flow_l.blocks.0.flows.0.coupling.net.2.bias", "flow_l.blocks.0.flows.0.coupling.net.4.scale", "flow_l.blocks.0.flows.0.coupling.net.4.conv.weight", "flow_l.blocks.0.flows.0.coupling.net.4.conv.bias", "flow_l.blocks.0.flows.1.actnorm.loc", "flow_l.blocks.0.flows.1.actnorm.scale", "flow_l.blocks.0.flows.1.actnorm.initialized", "flow_l.blocks.0.flows.1.invconv.weight", "flow_l.blocks.0.flows.1.coupling.net.0.weight", "flow_l.blocks.0.f"flow_l.blocks.0.flows.21.coupling.net.4.conv.bias", "flow_l.blocks.0.flows.22.actnorm.loc", "flow_l.blocks.0.flows.22.actnorm.scale", "flow_l.blocks.0.flows.22.actnorm.initialized", "flow_l.blocks.0.flows.22.invconv.weight", w_a.blocks.0.flows.29.coupling.net.2.weight", "flow_a.blocks.0.flows.29.coupling.net.2.bias", "flow_a.blocks.0.flows.29.coupling.net.4.scale", 
...
"flow_a.blocks.0.flows.29.coupling.net.4.conv.weight", "flow_a.blocks.0.flows.29.coupling.net.4.conv.bias", "flow_a.blocks.0.flows.30.actnorm.loc", "flow_a.blocks.0.flows.30.actnorm.scale", "flow_a.blocks.0.flows.30.actnorm.initialized", "flow_a.blocks.0.flows.30.invconv.weight", "flow_a.blocks.0.flows.30.coupling.net.0.weight", "flow_a.blocks.0.flows.30.coupling.net.0.bias", "flow_a.blocks.0.flows.30.coupling.net.2.weight", "weight_v.weight", "weight_v.bias", "weight_a.weight", "weight_a.bias". 
	Unexpected key(s) in state_dict: "text_model.model.embeddings.position_ids". 

how to solve it :((

**Comment by mdswyz** [comment]
Do you run the codes with the default settings? This seems to load the pretrained model with some errors.

**Comment by Duyih25** [comment]
when I run the code without using pretrained, result is very poor, it cannot get the performance like result you wrote in the paper

**Comment by Dawn-js** [comment]
您好，您是否解决了这个问题？

**Comment by artemisp** [comment]
Add `k = k.replace('text_model.model.embeddings.position_ids', 'text_model.model.embeddings.position_embeddings')`
under line 36 in DICMOR.py
