### ISSUE TITLE
fixed missing and random missing

### ISSUE THREAD

**Issue by lywinaaa** [mdswyz/DiCMoR#4]
hello，I saw in your article that you used fixed missing and random missing for incomplete settings, but I seem to have only seen your fixed missing operation in the code. Maybe I didn't notice the details.

**Comment by mdswyz** [comment]
Hello, Thanks for your attention. Maybe you've misunderstood, this repository only provides random missing settings, the missing rate (mr) could be set in train.py. The fixed missing is easy to set manually, so we do not provide.

**Comment by lywinaaa** [comment]
Sorry, this is my problem.
